import assert from 'node:assert/strict';
import test from 'node:test';
import { MOBILE_PROTOCOL_VERSION, callerHasCapability, createMobileCommand, mobileCapabilityFor, mobileOperationRequiresMutation, validateMobileCommand, validateMobileCursor, normalizeMobileAppearance } from './mobileProtocol';
const caller={deviceId:'phone-dave',capabilities:['execute','view'] as const};
const base={protocolVersion:MOBILE_PROTOCOL_VERSION,commandId:'cmd-12345678',issuedAt:'2026-09-09T12:00:00.000Z',caller,target:{hostId:'host-mac',projectId:'praxis'},operation:'workflowRuns.start' as const,payload:{workflowId:'workflow-1',task:'Run the work'}};
test('maps operations to capabilities',()=>{assert.equal(mobileCapabilityFor('workflowRuns.start'),'execute');assert.equal(mobileCapabilityFor('workflowGates.approve'),'approve');assert.equal(mobileOperationRequiresMutation('workflowRuns.start'),true);assert.equal(mobileOperationRequiresMutation('workflowRuns.get'),false);assert.equal(callerHasCapability(caller,'workflowRuns.start'),true);assert.equal(callerHasCapability(caller,'workflowGates.approve'),false);});
test('creates and validates envelope',()=>{const command=createMobileCommand(base);assert.equal(command.protocolVersion,1);assert.deepEqual(validateMobileCommand(command),{ok:true});});
test('rejects malformed and under-scoped commands',()=>{assert.equal(validateMobileCommand({...base,commandId:'short'}).ok,false);const forbidden=validateMobileCommand({...base,caller:{deviceId:'phone-dave',capabilities:['view'] as const}});assert.equal(forbidden.ok,false);if(!forbidden.ok)assert.equal(forbidden.error.code,'forbidden');const incomplete=validateMobileCommand({...base,target:{hostId:'host-mac'}});assert.equal(incomplete.ok,false);if(!incomplete.ok)assert.equal(incomplete.error.code,'invalid-envelope');});
test('validates cursors',()=>{assert.equal(validateMobileCursor({hostId:'host-mac',sequence:0}),undefined);assert.equal(validateMobileCursor({hostId:'',sequence:1})?.code,'invalid-envelope');assert.equal(validateMobileCursor({hostId:'host-mac',sequence:-1})?.code,'invalid-envelope');});
test('revision-2 reads are view-only and never mutate',()=>{for(const operation of ['host.info','providers.list','models.list','sessions.usage','access.get'] as const){assert.equal(mobileCapabilityFor(operation),'view');assert.equal(mobileOperationRequiresMutation(operation),false);}assert.equal(callerHasCapability({deviceId:'phone-dave',capabilities:['view']},'providers.list'),true);});
test('sessions.configure is an execute-capability mutation',()=>{assert.equal(mobileCapabilityFor('sessions.configure'),'execute');assert.equal(mobileOperationRequiresMutation('sessions.configure'),true);});

const appearanceColors={bg:'#100e0b',bgElevated:'#2C2620',bgSunken:'#0b0907',bgInput:'#211c17',border:'#443a30',borderStrong:'#6c5b4a',text:'#f0e7d8',textSecondary:'#cdbfae',textTertiary:'#958878',accent:'#c6431f',accentContrast:'#fffdf8',success:'#3fb950',warning:'#d29922',danger:'#e2766d'};
test('normalizes a desktop appearance and lower-cases its colours',()=>{const appearance=normalizeMobileAppearance({themeId:'praxis-dark',themeName:'Praxis Dark',mode:'dark',colors:appearanceColors});assert.equal(appearance?.colors.bgElevated,'#2c2620');assert.equal(appearance?.themeName,'Praxis Dark');assert.equal(normalizeMobileAppearance({themeId:'x',mode:'dark',colors:appearanceColors})?.themeName,'x');});
test('drops an appearance with a missing or non-hex colour',()=>{assert.equal(normalizeMobileAppearance({themeId:'x',mode:'dark',colors:{...appearanceColors,accent:'red'}}),undefined);assert.equal(normalizeMobileAppearance({themeId:'x',mode:'dark',colors:{...appearanceColors,danger:undefined}}),undefined);assert.equal(normalizeMobileAppearance({themeId:'x',mode:'dim',colors:appearanceColors}),undefined);assert.equal(normalizeMobileAppearance('praxis-dark'),undefined);});
test('keeps a well-formed motif and drops a malformed one without losing the colours',()=>{const layer={svg:'<svg xmlns="http://www.w3.org/2000/svg" width="760" height="760"></svg>',width:760,height:760,anchor:'top-right',repeat:false};const kept=normalizeMobileAppearance({themeId:'github-dark',mode:'dark',colors:appearanceColors,motif:{opacity:0.27,layers:[layer,{...layer,anchor:'bottom-left'}]}});assert.equal(kept?.motif?.layers.length,2);assert.equal(kept?.motif?.layers[1]?.anchor,'bottom-left');for(const bad of [{opacity:0.3,layers:[{...layer,svg:'<script>'}]},{opacity:0.3,layers:[{...layer,anchor:'middle'}]},{opacity:0,layers:[layer]},{opacity:0.3,layers:[]}]){const appearance=normalizeMobileAppearance({themeId:'x',mode:'dark',colors:appearanceColors,motif:bad});assert.ok(appearance,'the colours still apply');assert.equal(appearance?.motif,undefined);}});
