include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: false
