<#
.SYNOPSIS
  Compile the Ticket Manager VS Code extension and package it as a .vsix.

.DESCRIPTION
  1. Ensures build-time dev dependencies (typescript + esbuild + vsce) are
     installed. The org's private npm registry can't always resolve these,
     so the install falls back to the public npm registry when needed.
  2. Bundles src/extension.ts via esbuild scripts/esbuild.mjs into out/.
  3. Packages the extension into a .vsix using @vscode/vsce.
  4. Generates the Frosty-Store-style sidecars (.json + .svg + .md) under
     artifacts/ alongside the .vsix, derived from package.json + EXTENSION.md.
     Authors don't handcraft any sidecar files.

  The .vsix is written to artifacts/ and can be installed with:
    code --install-extension artifacts/ticket-manager-<version>.vsix

.PARAMETER PublicRegistry
  Registry URL used when the default registry can't resolve the dev dependencies.

.EXAMPLE
  pwsh ./scripts/build.ps1
#>
[CmdletBinding()]
param(
  [string]$PublicRegistry = 'https://registry.npmjs.org/'
)

$ErrorActionPreference = 'Stop'

$extensionRoot = Split-Path -Parent $PSScriptRoot

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "  + $msg" -ForegroundColor Green }
function Write-Warn2($msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }

# BOM-less UTF-8 writer (Windows PowerShell's Set-Content -Encoding utf8 adds a BOM).
function Write-Utf8NoBom($path, $text) {
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $text, $enc)
}

# Derive the Frosty-Store-style sidecar files (.json, .svg, .md) from the
# in-repo package.json + EXTENSION.md + media/icon.svg. Writes to
# `$ArtifactsRoot`. Authors don't touch any of these by hand — they're
# regenerated by every build.
function Build-StoreSidecarFromPackage {
  param(
    [string]$PackageJsonPath,
    [string]$ExtensionRoot,
    [string]$ArtifactsRoot,
    [string]$PackageName,
    [string]$Version
  )

  if (-not (Test-Path $PackageJsonPath)) {
    throw "package.json not found at $PackageJsonPath"
  }
  $pkgRaw = Get-Content $PackageJsonPath -Raw
  $pkg = $pkgRaw | ConvertFrom-Json
  if (-not $PackageName) { $PackageName = [string]$pkg.name }
  if (-not $Version) { $Version = [string]$pkg.version }

  if ($PackageName -match '-preview$') {
    $displayPackageName = $PackageName -replace '-preview$', ''
  } else {
    $displayPackageName = $PackageName
  }

  $base = "$PackageName-$Version"

  # ---- Icon sidecar --------------------------------------------------------
  # Always emit SVG and a data URL alongside it so the store detail panel can
  # render the icon without an extra HTTP round-trip. The canonical source
  # lives at media/icon.svg; if absent we fall back to media/marketplace-icon.png
  # encoded as a data URL so the sidecar is still self-contained.
  $svgRelativePath = 'media/icon.svg'
  $svgFallbackPath = 'media/marketplace-icon.svg'
  $pngRelativePath = 'media/marketplace-icon.png'
  $iconSvgPath = Join-Path $ArtifactsRoot "$base.svg"
  $iconDataUrl = $null
  $resolvedIconSource = $null
  if (Test-Path (Join-Path $ExtensionRoot $svgRelativePath)) {
    $resolvedIconSource = $svgRelativePath
  } elseif (Test-Path (Join-Path $ExtensionRoot $svgFallbackPath)) {
    $resolvedIconSource = $svgFallbackPath
  }
  if ($resolvedIconSource) {
    $fullSource = Join-Path $ExtensionRoot $resolvedIconSource
    Copy-Item -Force $fullSource $iconSvgPath
    $bytes = [System.IO.File]::ReadAllBytes($fullSource)
    $iconDataUrl = 'data:image/svg+xml;base64,' + [Convert]::ToBase64String($bytes)
    Write-Ok "Icon -> $iconSvgPath"
  } elseif (Test-Path (Join-Path $ExtensionRoot $pngRelativePath)) {
    $fullSource = Join-Path $ExtensionRoot $pngRelativePath
    $bytes = [System.IO.File]::ReadAllBytes($fullSource)
    $iconDataUrl = 'data:image/png;base64,' + [Convert]::ToBase64String($bytes)
    Write-Warn2 "Icon source is a PNG ('$pngRelativePath'); prefer rendering via data URL. Add media/icon.svg for a vector copy."
  } else {
    Write-Warn2 "No icon source found (expected media/icon.svg or media/marketplace-icon.png); skipping icon sidecar."
  }

  # ---- Readme sidecar ------------------------------------------------------
  # The bundling convention is: if package.json has a top-level `markdown`
  # field (e.g. "EXTENSION.md"), the build copies that file alongside the
  # VSIX and embeds its bytes into the .json sidecar under "markdown".
  # Round-trip through System.IO.File.ReadAllText + UTF-8 to keep non-ASCII
  # characters (em-dashes, smart quotes) intact — PowerShell's native
  # `Get-Content -Raw` decodes as system codepage, which mojibakes multibyte
  # glyphs when later round-tripped through ConvertTo-Json.
  $markdownPath = $null
  if ($pkg.PSObject.Properties.Name -contains 'markdown' -and $pkg.markdown) {
    $markdownPath = Join-Path $ExtensionRoot ([string]$pkg.markdown)
  }
  $markdownText = ''
  $markdownSidecarPath = Join-Path $ArtifactsRoot "$base.md"
  if ($markdownPath -and (Test-Path $markdownPath)) {
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    $markdownText = [System.IO.File]::ReadAllText($markdownPath, $utf8)
    $markdownText = $markdownText -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($markdownSidecarPath, $markdownText, $utf8)
    Write-Ok "Readme -> $markdownSidecarPath"
  } else {
    if (Test-Path $markdownSidecarPath) { Remove-Item -Force $markdownSidecarPath }
  }

  # ---- Pre-extract the "What's New" section --------------------------------
  # The Frosty Store (and downstream consumers) renders only the latest
  # release (the first `### x.y` subheading) under the **What's New** section
  # of the detail page rather than the whole changelog. Doing the slice here
  # in PowerShell means the shipped JSON carries a small `whatsNew` blob the
  # runtime reads directly — no extraction logic at render time, smaller
  # payload, smaller chance of transit corruption.
  #
  # Algorithm: walk lines, find `## What's New`, then start at the first
  # `### x.y` heading inside it and stop before the next heading at any
  # level 2 or deeper (`## ` or `### ...`) — so a trailing `## Known
  # limitations` or `## Configuration` block doesn't leak into the slice.
  $whatsNewText = ''
  if ($markdownText) {
    $allLines = $markdownText -split "`n"
    $wnStart = -1
    for ($i = 0; $i -lt $allLines.Length; $i++) {
      if ($allLines[$i] -match '^##\s+What.?s New\s*$') {
        $wnStart = $i + 1
        break
      }
    }
    if ($wnStart -ge 0) {
      $wnContentStart = -1
      for ($j = $wnStart; $j -lt $allLines.Length; $j++) {
        if ($allLines[$j] -match '^###\s+\S') { $wnContentStart = $j; break }
      }
      $wnEnd = $allLines.Length
      if ($wnContentStart -ge 0) {
        for ($k = $wnContentStart + 1; $k -lt $allLines.Length; $k++) {
          if ($allLines[$k] -match '^##\s+\S') { $wnEnd = $k; break }
        }
        $whatsNewText = ($allLines[$wnContentStart..($wnEnd - 1)] -join "`n").Trim()
      }
    }
  }

  # ---- JSON sidecar --------------------------------------------------------
  # Fields mirror what the Frosty Store detail panel renders: displayName,
  # description, categories, keywords, license, engines vscode, repository,
  # homepage, author, plus `icon.dataUrl` for self-contained SVG render and
  # the `markdown` body. Other extensions can mirror this convention; the
  # schema is intentionally not versioned yet.
  function AsArray {
    param($v)
    if ($null -eq $v) { return @() }
    if ($v -is [System.Array]) { return @($v) }
    return ,$v
  }

  $categories = @()
  if ($pkg.PSObject.Properties.Name -contains 'categories' -and $pkg.categories) {
    $categories = @($pkg.categories | Where-Object { $_ } | ForEach-Object { [string]$_ })
  }

  $keywords = @()
  if ($pkg.PSObject.Properties.Name -contains 'keywords' -and $pkg.keywords) {
    $keywords = @($pkg.keywords | Where-Object { $_ } | ForEach-Object { [string]$_ })
  }

  $enginesVscode = $null
  if ($pkg.PSObject.Properties.Name -contains 'engines' -and $pkg.engines) {
    if ($pkg.engines.PSObject.Properties.Name -contains 'vscode') {
      $enginesVscode = [string]$pkg.engines.vscode
    }
  }

  $repositoryUrl = $null
  if ($pkg.PSObject.Properties.Name -contains 'repository' -and $pkg.repository) {
    if ($pkg.repository -is [string]) {
      $repositoryUrl = [string]$pkg.repository
    } elseif ($pkg.repository.PSObject.Properties.Name -contains 'url') {
      $repositoryUrl = [string]$pkg.repository.url
    }
  }

  $homepage = $null
  if ($pkg.PSObject.Properties.Name -contains 'homepage' -and $pkg.homepage) {
    $homepage = [string]$pkg.homepage
  }

  $license = $null
  if ($pkg.PSObject.Properties.Name -contains 'license' -and $pkg.license) {
    if ($pkg.license -is [string]) {
      $license = [string]$pkg.license
    } elseif ($pkg.license.PSObject.Properties.Name -contains 'type') {
      $license = [string]$pkg.license.type
    }
  }

  $author = $null
  if ($pkg.PSObject.Properties.Name -contains 'author' -and $pkg.author) {
    if ($pkg.author -is [string]) {
      $author = [string]$pkg.author
    } elseif ($pkg.author.PSObject.Properties.Name -contains 'name') {
      $author = [string]$pkg.author.name
    }
  }

  $sidecar = [ordered]@{
    name          = $displayPackageName
    packageName   = [string]$pkg.name
    displayName   = if ($pkg.PSObject.Properties.Name -contains 'displayName' -and $pkg.displayName) { [string]$pkg.displayName } else { $displayPackageName }
    version       = [string]$pkg.version
    publisher     = if ($pkg.PSObject.Properties.Name -contains 'publisher' -and $pkg.publisher) { [string]$pkg.publisher } else { $null }
    author        = $author
    description   = if ($pkg.PSObject.Properties.Name -contains 'description' -and $pkg.description) { [string]$pkg.description } else { '' }
    categories    = $categories
    keywords      = $keywords
    enginesVscode = $enginesVscode
    license       = $license
    repositoryUrl = $repositoryUrl
    homepage      = $homepage
    icon          = if ($iconDataUrl) {
      $iconRecord = [ordered]@{ dataUrl = $iconDataUrl }
      if ($resolvedIconSource) { $iconRecord['path'] = $resolvedIconSource }
      $iconRecord
    } else { $null }
    markdown      = $markdownText
    whatsNew      = $whatsNewText
  }

  # Use ConvertTo-Json so the deeply structured shape is emitted deterministically,
  # then post-process the embedded markdown so non-ASCII characters survive the
  # round-trip. PowerShell serialises high-codepoint characters via UTF-8 byte
  # sequences which JSON decoders would surface as mojibake; the cleanest
  # workaround is to parse the emitted JSON and rewrite every \uXXXX escape
  # back to the actual UTF-16 codepoint.
  $json = (ConvertTo-Json -InputObject $sidecar -Depth 10)
  $json = ($json -replace "`r`n", "`n")
  $unescaped = [regex]::Replace($json, {
    param($m)
    $code = [Convert]::ToInt32($m.Groups[1].Value, 16)
    return [char]::ConvertFromUtf32($code)
  }, '\\u([0-9A-Fa-f]{4})')
  $json = $unescaped

  $jsonPath = Join-Path $ArtifactsRoot "$base.json"
  Write-Utf8NoBom $jsonPath $json
  Write-Ok "Metadata -> $jsonPath"
}


Push-Location $extensionRoot
try {
  # --- 1. Ensure dev dependencies ---------------------------------------------
  $tsc = Join-Path $extensionRoot 'node_modules\typescript\bin\tsc'
  $esbuildScript = Join-Path $extensionRoot 'esbuild.mjs'
  $haveTypes = (Test-Path (Join-Path $extensionRoot 'node_modules\@types\node')) -and
               (Test-Path (Join-Path $extensionRoot 'node_modules\@types\vscode'))

  if (-not (Test-Path $tsc) -or -not $haveTypes -or -not (Test-Path $esbuildScript)) {
    Write-Step 'Installing build dependencies'
    & npm install
    if ($LASTEXITCODE -ne 0) {
      Write-Warn2 "Default registry install failed; retrying via $PublicRegistry"
      & npm install --registry $PublicRegistry
      if ($LASTEXITCODE -ne 0) { throw 'Failed to install build dependencies.' }
    }
    Write-Ok 'Dependencies installed'
  } else {
    Write-Ok 'Dependencies already present'
  }

  if (-not (Test-Path $tsc)) { throw "TypeScript compiler not found at $tsc." }
  if (-not (Test-Path $esbuildScript)) { throw "esbuild.mjs not found at $esbuildScript." }

  # --- 2. Type-check ---------------------------------------------------------
  Write-Step 'Type-checking (tsc --noEmit)'
  & node $tsc --noEmit -p $extensionRoot
  if ($LASTEXITCODE -ne 0) { throw 'Type-check failed.' }
  Write-Ok 'Type-check clean'

  # --- 3. Bundle via esbuild (production) ------------------------------------
  Write-Step 'Bundling (esbuild -> out/extension.js)'
  & node $esbuildScript --production
  if ($LASTEXITCODE -ne 0) { throw 'esbuild bundling failed.' }

  $entry = Join-Path $extensionRoot 'out\extension.js'
  if (-not (Test-Path $entry)) { throw "esbuild produced no output at $entry" }
  Write-Ok "Bundled $entry"

  # --- 4. Package the .vsix --------------------------------------------------
  Write-Step 'Packaging .vsix'
  $pkg = Get-Content (Join-Path $extensionRoot 'package.json') -Raw | ConvertFrom-Json
  $artifactsRoot = Join-Path $extensionRoot 'artifacts'
  New-Item -ItemType Directory -Force $artifactsRoot | Out-Null
  $vsixName = "$($pkg.name)-$($pkg.version).vsix"
  $vsixPath = Join-Path $artifactsRoot $vsixName

  if (Test-Path $vsixPath) { Remove-Item -Force $vsixPath }

  # Resolve baseContentUrl / baseImagesUrl so vsce can rewrite any relative
  # links in README.md (e.g. docs/user-guide.md) into absolute URLs on our
  # self-hosted GitLab project. The trailing `-/raw/<branch>/` is the GitLab
  # raw file path that vsce's `--baseContentUrl` expects.
  $baseBranch = if ($env:CI_COMMIT_REF_NAME) { $env:CI_COMMIT_REF_NAME } else { 'main' }
  $remoteOrigin = (git remote get-url origin 2>$null)
  if ($remoteOrigin -match '^(?:https?://|git@)([^/]+)[/:](.+?)(?:\.git)?$') {
    $originHost = $Matches[1]
    $originPath = $Matches[2]
    $baseContentUrl = "https://$originHost/$originPath/-/raw/$baseBranch/"
    $baseImagesUrl = "https://$originHost/$originPath/-/raw/$baseBranch/"
  } else {
    $baseContentUrl = $null
    $baseImagesUrl = $null
  }

  # --no-dependencies: dev deps are dev-only and the runtime payload is the
  # self-contained out/ bundle, so vsce must not run a production npm install
  # (the private registry can't resolve the dev dependency tree).
  $vsceArgs = @(
    'package',
    '--no-dependencies',
    '--skip-license',
    '--allow-missing-repository',
    '--out', $vsixPath
  )
  if ($baseContentUrl) { $vsceArgs += @('--baseContentUrl', $baseContentUrl) }
  if ($baseImagesUrl)  { $vsceArgs += @('--baseImagesUrl',  $baseImagesUrl)  }

  & npx --yes --registry $PublicRegistry @vscode/vsce @vsceArgs
  if ($LASTEXITCODE -ne 0) { throw 'vsce package failed.' }
  if (-not (Test-Path $vsixPath)) { throw "vsce reported success but $vsixPath is missing." }
  Write-Ok "Packaged -> $vsixPath"

  # --- 4.5 Build the store-side metadata sidecars --------------------------
  Write-Step 'Generating metadata sidecars'
  Build-StoreSidecarFromPackage `
    -PackageJsonPath (Join-Path $extensionRoot 'package.json') `
    -ExtensionRoot $extensionRoot `
    -ArtifactsRoot $artifactsRoot `
    -PackageName $pkg.name `
    -Version $pkg.version

  # --- 5. Bundle the standalone installer next to the .vsix ------------------
  # So the artifacts/ folder is self-contained and can be distributed as-is:
  # the .vsix + a self-contained install script + a short README.
  Write-Step 'Bundling standalone installer'
  $installDistSrc = Join-Path $extensionRoot 'scripts\install-dist.ps1'
  if (Test-Path $installDistSrc) {
    Copy-Item -Force $installDistSrc (Join-Path $artifactsRoot 'install.ps1')
    Write-Ok "Installer -> $(Join-Path $artifactsRoot 'install.ps1')"
  } else {
    Write-Warn2 "scripts\install-dist.ps1 not found; skipping installer bundle."
  }

  $readmeText = @"
Ticket Manager $($pkg.version)
======================

This folder contains everything needed to install Ticket Manager:

  - $vsixName   (the extension)
  - install.ps1                     (installer)

To install (Windows PowerShell), from this folder run:

  pwsh ./install.ps1

That installs the extension into every detected VS Code-family editor
(VS Code, VS Code Insiders, Cursor). Then fully restart your editor(s).

After installing:
  1. Open the Ticket Manager activity-bar entry and pick a backend (Jira,
     Demo, Live Folder, File, or GitLab).
  2. Configure Connections & Boards.

To uninstall:

  pwsh ./install.ps1 -Uninstall

Manual install (if you prefer): in the Extensions view, choose the '...'
menu -> "Install from VSIX", pick $vsixName.
"@
  Write-Utf8NoBom (Join-Path $artifactsRoot 'README.txt') $readmeText
  Write-Ok "Readme -> $(Join-Path $artifactsRoot 'README.txt')"

  Write-Host ''
  Write-Host 'VSIX ready.' -ForegroundColor Cyan
  Write-Host "  $vsixPath"
  Write-Host ''
  Write-Host 'Distributable bundle in artifacts/ (share the whole folder):' -ForegroundColor Cyan
  Write-Host "  $vsixName + install.ps1 + README.txt"
  Write-Host ''
  Write-Host 'To install locally:' -ForegroundColor Cyan
  Write-Host '  pwsh ./scripts/install.ps1'
  Write-Host ''
  Write-Host 'Or install the .vsix directly:' -ForegroundColor Cyan
  Write-Host "  code --install-extension `"$vsixPath`""
}
finally {
  Pop-Location
}
