<#
.SYNOPSIS
  Upload the Ticket Manager release artefacts (VSIX + sidecar metadata) to
  this project's GitLab Generic Package Registry.

.DESCRIPTION
  Uploads the matched artefacts under packages/generic/<package-name>/<version>/:
    - ticket-manager-<version>.vsix   – the extension
    - ticket-manager-<version>.json   – store metadata (displayName, description, icon data URL, markdown)
    - ticket-manager-<version>.svg    – extension icon (mirrors media/icon.svg)
    - ticket-manager-<version>.md     – extension readme (mirrors EXTENSION.md)
  Sidecars are generated by scripts/build.ps1; authors do not handcraft them.

  Auth (first match wins):
    1. -Token argument
    2. $env:GITLAB_TOKEN / $env:GITLAB_PRIVATE_TOKEN / $env:CI_JOB_TOKEN
    3. glab config get token (if glab is installed)

.PARAMETER VsixPath
  Path to the .vsix to derive the version from. Defaults to the latest
  artifacts/ticket-manager-*.vsix. Sidecars of the same version are
  uploaded alongside.

.PARAMETER SidecarDir
  Directory containing sidecar files (default: the same directory as the
  .vsix, i.e. artifacts/).

.EXAMPLE
  pwsh ./scripts/build.ps1
  pwsh ./scripts/publish-gitlab.ps1
#>
[CmdletBinding()]
param(
  [string]$VsixPath,
  [string]$ProjectId,
  [string]$ApiUrl,
  [string]$Token,
  [string]$PackageName = 'ticket-manager',
  [string]$SidecarDir
)

$ErrorActionPreference = 'Stop'

$extensionRoot = Split-Path -Parent $PSScriptRoot
Push-Location $extensionRoot
try {
  function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
  function Write-Ok($msg) { Write-Host "  + $msg" -ForegroundColor Green }

  function Resolve-GitLabToken {
    param([string]$Explicit)
    if ($Explicit) { return $Explicit.Trim() }
    foreach ($key in @('GITLAB_TOKEN', 'GITLAB_PRIVATE_TOKEN', 'CI_JOB_TOKEN')) {
      $value = [Environment]::GetEnvironmentVariable($key)
      if ($value -and $value.Trim()) { return $value.Trim() }
    }
    if (Get-Command glab -ErrorAction SilentlyContinue) {
      $fromConfig = & glab config get token --host git.tools.dev.assaabloyglobalsolutions.net 2>$null
      if ($fromConfig -and "$fromConfig".Trim() -and "$fromConfig" -notmatch 'USAGE') {
        return "$fromConfig".Trim()
      }
      $hostName = $null
      $origin = git remote get-url origin 2>$null
      if ($origin -match '^https?://([^/]+)/') { $hostName = $Matches[1] }
      elseif ($origin -match '^git@([^:]+):') { $hostName = $Matches[1] }
      if ($hostName) {
        $fromConfig = & glab config get token --host $hostName 2>$null
        if ($fromConfig -and "$fromConfig".Trim() -and "$fromConfig" -notmatch 'USAGE') {
          return "$fromConfig".Trim()
        }
      }
    }
    return $null
  }

  function Publish-PackageFile {
    param(
      [string]$FilePath,
      [string]$UploadUrl,
      [hashtable]$Headers
    )
    $name = Split-Path -Leaf $FilePath
    Write-Host "  Uploading $name"
    $response = Invoke-WebRequest -Method Put -Uri $UploadUrl -InFile $FilePath -Headers $Headers -UseBasicParsing
    if ($response.StatusCode -notin 200, 201) {
      throw "Upload failed for $name with HTTP $($response.StatusCode): $($response.Content)"
    }
    Write-Ok $name
  }

  if (-not $VsixPath) {
    $candidates = Get-ChildItem -Path (Join-Path $extensionRoot 'artifacts') -Filter 'ticket-manager-*.vsix' -ErrorAction SilentlyContinue |
      Sort-Object LastWriteTime -Descending
    if (-not $candidates) {
      throw "No artifacts/ticket-manager-*.vsix found. Run: npm run build"
    }
    $VsixPath = $candidates[0].FullName
  }
  if (-not (Test-Path -LiteralPath $VsixPath)) {
    throw "VSIX not found: $VsixPath"
  }

  $fileName = Split-Path -Leaf $VsixPath
  if ($fileName -notmatch '^(ticket-manager(?:-preview)?)-(.+)\.vsix$') {
    throw "Unexpected VSIX name '$fileName' (expected ticket-manager[-preview]-<version>.vsix)."
  }
  $prefix = $Matches[1]
  $version = $Matches[2]

  $Token = Resolve-GitLabToken -Explicit $Token
  if (-not $Token) {
    throw @"
No GitLab token found. Set one of:
  -Token <pat>
  `$env:GITLAB_TOKEN  (personal/project access token with api scope)
  `$env:CI_JOB_TOKEN  (inside a GitLab CI job)
"@
  }

  $origin = (git remote get-url origin 2>$null)
  if (-not $origin) { throw 'git remote origin is not set.' }

  $hostName = $null
  $projectPath = $null
  if ($origin -match '^git@([^:]+):(.+?)(?:\.git)?$') {
    $hostName = $Matches[1]
    $projectPath = $Matches[2]
  } elseif ($origin -match '^https?://([^/]+)/(.+?)(?:\.git)?$') {
    $hostName = $Matches[1]
    $projectPath = $Matches[2]
  } else {
    throw "Unrecognized origin URL: $origin"
  }

  if (-not $ApiUrl) {
    $ApiUrl = "https://$hostName/api/v4"
  }
  if (-not $ProjectId) {
    $ProjectId = [uri]::EscapeDataString($projectPath)
  }

  $isJobToken = $env:CI_JOB_TOKEN -and ($Token -eq $env:CI_JOB_TOKEN)
  $headers = if ($isJobToken) {
    @{ 'JOB-TOKEN' = $Token }
  } else {
    @{ 'PRIVATE-TOKEN' = $Token }
  }

  $baseUrl = "$ApiUrl/projects/$ProjectId/packages/generic/$PackageName/$version"
  Write-Step "Publishing ${PackageName}@${version} → Package Registry"

  $sidecarsDir = if ($SidecarDir) { $SidecarDir } else { (Split-Path -Parent $VsixPath) }
  $artefactPaths = @()
  if (Test-Path $VsixPath) { $artefactPaths += (Resolve-Path $VsixPath).Path }
  $candidates = Get-ChildItem -Path $sidecarsDir -Filter "$prefix-$version.*" -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne (Split-Path -Leaf $VsixPath) } |
    Sort-Object Name
  foreach ($c in $candidates) { $artefactPaths += $c.FullName }

  $vsixFile = Split-Path -Leaf $VsixPath
  if (-not ($artefactPaths | Where-Object { (Split-Path -Leaf $_) -eq $vsixFile })) {
    throw "VSIX '$vsixFile' was not found in the artefact set; refusing to publish."
  }

  foreach ($artefact in $artefactPaths) {
    $artefactName = Split-Path -Leaf $artefact
    Publish-PackageFile -FilePath $artefact -UploadUrl "$baseUrl/$artefactName" -Headers $headers
  }

  $summaryNames = ($artefactPaths | ForEach-Object { Split-Path -Leaf $_ }) -join ', '
  Write-Ok "Published ${PackageName}@${version} ($summaryNames)"
  Write-Host ''
  Write-Host "View: https://$hostName/$projectPath/-/packages" -ForegroundColor Cyan
}
finally {
  Pop-Location
}
