import { useState } from 'react';
import type { AgentToolMode, Board, ProjectRecord, ProjectStartingPoint, ProjectType } from '@praxis/core';
// Deep import on purpose: `@praxis/core`'s barrel pulls in node-only services
// (chokidar, node:fs) that cannot be bundled for the browser — importing
// PROJECT_BRIEF_FIELDS from the package root fails the vite build.
import { PROJECT_BRIEF_FIELDS } from '@praxis/core/out/projects/projectTemplates';

export function ProjectHome({ project, boards, onChanged, onOpenBoard, onOpenGit }: { project: ProjectRecord; boards: Board[]; onChanged: (project: ProjectRecord) => void; onOpenBoard: (boardId: string) => void; onOpenGit: () => void }) {
  const [editing, setEditing] = useState(false); const [type, setType] = useState<ProjectType>(project.type); const [toolMode, setToolMode] = useState<AgentToolMode>(project.defaultAiToolMode); const [purpose, setPurpose] = useState(project.purpose); const [brief, setBrief] = useState(project.brief); const [error, setError] = useState<string>(); const [attachMode, setAttachMode] = useState<ProjectStartingPoint>('existing-folder'); const [attachPath, setAttachPath] = useState(''); const [folderName, setFolderName] = useState('');
  const defaultBoard = boards.find(board => board.id === project.defaultBoardId);
  const plansBoard = project.linkedBoards.map(link => boards.find(board => board.id === link.boardId && board.connectionId === link.connectionId)).find(Boolean);
  const primaryBoard = plansBoard ?? defaultBoard;
  const candidates = boards.filter(board => !board.connectionId?.startsWith('project:') && board.connectionId && !project.linkedBoards.some(link => link.connectionId === board.connectionId && link.boardId === board.id));
  const save = async () => { try { onChanged(await window.praxis.projects.update(project.id, { type, purpose, brief, defaultAiToolMode: toolMode })); setEditing(false); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  const chooseAttach = async () => { const value = await window.praxis.dialog.pickFolder(attachMode === 'new-folder' ? 'Choose parent folder' : 'Choose existing project folder'); if (value) setAttachPath(value); };
  const attach = async () => { try { const result = await window.praxis.projects.attachFolder(project.id, { startingPoint: attachMode as 'new-folder' | 'existing-folder', folderPath: attachPath, folderName: folderName || undefined, createProjectFile: true }); onChanged(result.project); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  return <div className="project-home" data-testid="project-home"><header className="project-home-hero"><div><span className="project-type-badge">{project.type}</span><h1>{project.name}</h1><p>{project.key} · Created {new Date(project.createdAt).toLocaleDateString()}</p></div><button className="btn btn-primary" disabled={!primaryBoard} onClick={() => primaryBoard && onOpenBoard(primaryBoard.id)}>{plansBoard ? 'Open plans board' : 'Open default board'}</button></header>
    {project.projectFileStatus === 'retained' && <div className="notice-card">An existing PROJECT.md was retained. The app project record remains authoritative.</div>}
    <div className="project-home-grid"><section className="project-panel"><div className="section-heading"><h2>Project brief</h2>{editing ? <div><button className="btn" onClick={() => { setEditing(false); setType(project.type); setToolMode(project.defaultAiToolMode); setPurpose(project.purpose); setBrief(project.brief); }}>Cancel</button><button className="btn btn-primary" onClick={save}>Save</button></div> : <button className="btn" onClick={() => setEditing(true)}>Edit</button>}</div>{editing && <><label className="field"><span>Project type</span><select className="input" value={type} onChange={e => setType(e.target.value as ProjectType)}><option value="software">Software Development</option><option value="product">Product Development</option><option value="research">Research</option><option value="experiment">Experiment / Prototype</option></select></label><label className="field"><span>Default session tools</span><select className="input" value={toolMode} disabled={!project.workspaceFolder} onChange={e => setToolMode(e.target.value as AgentToolMode)}>{!project.workspaceFolder && <option value="project-only">Project-board tools only</option>}<option value="read-only">Read-only tools</option><option value="full">Full tools</option></select></label></>}<label className="field"><span>Purpose</span>{editing ? <textarea className="input textarea" value={purpose} onChange={e => setPurpose(e.target.value)} /> : <p>{project.purpose || 'Not specified'}</p>}</label>{PROJECT_BRIEF_FIELDS[editing ? type : project.type].map(field => <div className="brief-value" key={field.key}><strong>{field.label}</strong>{editing ? <textarea className="input textarea" value={brief[field.key] ?? ''} onChange={e => setBrief(current => ({ ...current, [field.key]: e.target.value }))} /> : <p>{project.brief[field.key] || 'Not specified'}</p>}</div>)}</section>
      <aside className="project-home-aside"><section className="project-panel"><h2>Workspace</h2>{project.workspaceFolder ? <><code className="path-block">{project.workspaceFolder}</code>{project.folderInspection && <div className="detection-list"><span>{project.folderInspection.hasGit ? 'Git repository' : 'No Git repository'}</span><span>{project.folderInspection.languages.join(', ') || 'No languages detected'}</span><span>{project.folderInspection.frameworks.join(', ') || 'No frameworks detected'}</span><span>{project.folderInspection.manifests.join(', ') || 'No manifests detected'}</span></div>}</> : <><p>Attach a folder to enable file and shell tools.</p><div className="segmented"><button className={attachMode === 'existing-folder' ? 'segmented-btn active' : 'segmented-btn'} onClick={() => setAttachMode('existing-folder')}>Existing</button><button className={attachMode === 'new-folder' ? 'segmented-btn active' : 'segmented-btn'} onClick={() => setAttachMode('new-folder')}>New</button></div><div className="folder-picker"><input className="input" value={attachPath} readOnly /><button className="btn" onClick={chooseAttach}>Choose…</button></div>{attachMode === 'new-folder' && <input className="input" placeholder="Folder name" value={folderName} onChange={e => setFolderName(e.target.value)} />}<button className="btn btn-primary" disabled={!attachPath} onClick={attach}>Attach folder</button></>}</section>
        <section className="project-panel"><h2>Planning sources</h2>{project.linkedBoards.length === 0 && <p className="muted">No board is linked yet. Boards connected to this project will appear here.</p>}{project.linkedBoards.map(link => { const board = boards.find(item => item.id === link.boardId && item.connectionId === link.connectionId); return <div className="linked-board" key={`${link.connectionId}:${link.boardId}`}><div><strong>{link.displayName}</strong><small>{link.connectionId.startsWith('project-plans-') ? 'Local plans · read-only' : 'Linked board'}</small></div><div className="linked-board-actions">{board && <button className="btn btn-primary" onClick={() => onOpenBoard(board.id)}>Open board</button>}{!link.connectionId.startsWith('project-plans-') && <button className="btn" onClick={async () => onChanged(await window.praxis.projects.unlinkBoard(project.id, link.connectionId, link.boardId))}>Unlink</button>}</div></div>})}{candidates.length > 0 && <select className="input" defaultValue="" onChange={async e => { const board = candidates.find(item => `${item.connectionId}:${item.id}` === e.target.value); if (board?.connectionId) onChanged(await window.praxis.projects.linkBoard(project.id, { connectionId: board.connectionId, boardId: board.id, displayName: board.name })); e.target.value = ''; }}><option value="">Link an existing board…</option>{candidates.map(board => <option key={`${board.connectionId}:${board.id}`} value={`${board.connectionId}:${board.id}`}>{board.name}</option>)}</select>}</section></aside></div>{error && <div className="form-error">{error}</div>}</div>;
}
